base/urls.py
from django.urls import path
from .views import IndexView, CommunityView, InforView, ErrorView, HelpCenterView


app_name = 'base'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('community/', CommunityView.as_view(), name='community'),
    path('information/', InforView.as_view(), name='infor-index'),
    path('error/', ErrorView.as_view(), name='error-index'),
    path('help-center/', HelpCenterView.as_view(), name='help-center')



]

bms/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostDeleteView,
    NewsListView,
    NewsDetailView,
    NewsCreateView,
    NewsUpdateView,
    NewsDeleteView,
    ToolsListView,
    ToolsDetailView,
    ToolsCreateView,
    ToolsDeleteView,
    SkillsView,
    SkillsDetailView,
    SkillsCreateView,
    SkillsDeleteView,
    ServiceListView,
    CreateServiceView,
    DeleteServiceView,
    DetailServiceView,
    CreateRequestServiceView,
    RequestView,
    DetailUserRequestView,
    DeleteUserRequestView,
    CreateResponseView,
    DetailResponseView,
    ListResponseView,
    DeleteResponseView,
    BmsHubView,


)

app_name = 'bms'

urlpatterns = [
    path('bms/', BmsHubView.as_view(), name='bms-hub'),
    #post
    path('post/', PostListView.as_view(), name='post-list'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
    path('create/post/', PostCreateView.as_view(), name='post-create'),
    path('delete/post/<slug:slug>/', PostDeleteView.as_view(), name='delete-post'),




    #news
    path('news/', NewsListView.as_view(), name='news-list'),
    path('news/<slug:slug>/', NewsDetailView.as_view(), name='news-detail'),
    path('create/news/', NewsCreateView.as_view(), name='news-create'),
    path('update/news/<slug:slug>/', NewsUpdateView.as_view(), name='news-update'),
    path('delete/news/<slug:slug>/', NewsDeleteView.as_view(), name='delete-news'),


    #tools
    path('tools/', ToolsListView.as_view(), name='tools-list'),
    path('tools/<slug:slug>/', ToolsDetailView.as_view(), name='tools-detail'),
    path('create/tools/', ToolsCreateView.as_view(), name='tools-create'),
    path('delete/tools/<slug:slug>/', ToolsDeleteView.as_view(), name='delete-tools'),



    #skills
    path('skills/', SkillsView.as_view(), name='skills-list'),
    path('skills/<slug:slug>/', SkillsDetailView.as_view(), name='skills-detail'),
    path('create/skills/', SkillsCreateView.as_view(), name='skills-create'),
    path('delete/skills/<slug:slug>/', SkillsDeleteView.as_view(), name='delete-skills'),



    #SERVICE
    path('service/', ServiceListView.as_view(), name='service-list'),
    path('create/service/', CreateServiceView.as_view(), name='service-create'),

    path('delete/service/<slug:slug>/', DeleteServiceView.as_view(), name='delete-service'),
    path('detail/service/<slug:slug>/', DetailServiceView.as_view(), name='detail-service'),




    #requets

    path('create/request/', CreateRequestServiceView.as_view(), name='request-create'),
    path('request', RequestView.as_view(), name='request-list'),
    path('user/request/<slug:slug>/', DetailUserRequestView.as_view(), name='user-request'),
    path('delete/request/<slug:slug>/', DeleteUserRequestView.as_view(), name='delete-request'),




    #response

    path('create/response/<slug:slug>/', CreateResponseView.as_view(), name='response-create'),
    path('response/detail/<slug:slug>/', DetailResponseView.as_view(), name='detail-response'),
    path('list/response/', ListResponseView.as_view(), name='list-response'),
    path('delete/response/<slug:slug>/', DeleteResponseView.as_view(), name='delete-response'),




    ]

custom/urls.py
from django.urls import path
from .views import *


app_name = 'custom'

urlpatterns = [

    path('redirect/', RedirectAfterLoginView.as_view(), name='redirect_after_login'),
    path('delete-account/', DeleteAccountView.as_view(), name='delete-account'),
    path('settings/', SettingsView.as_view(), name='settings-menu'),
    path('users/', UsersListView.as_view(), name='users-list'),
    path('notify/', NotificationsView.as_view(), name='notify-settings'),
    path('profile/', ProfileView.as_view(), name='profile-settings'),
    path('help/', HelpView.as_view(), name='help-settings'),
    path('policies/', PoliciesView.as_view(), name='policy-settings'),


]

dashboard/urls.py
from django.urls import path
from .views import UserDashboardView, AgentDashboardView, ManagerDashboard, SuperDashboard

app_name = 'dashboard'
urlpatterns = [
    path('user_dashboard/', UserDashboardView.as_view(), name='user_dashboard' ),
    path('agent/', AgentDashboardView.as_view(), name='agent-dashboard'),
    path('manager/', ManagerDashboard.as_view(), name='manager-dashboard'),
    path('super/', SuperDashboard.as_view(), name='super-dash'),


]

editing/urls.py
from django.urls import path

from .views import *


app_name = 'editing'
urlpatterns = [
    path('edit-hub/', EditingHubView.as_view(), name='editing-hub'),
    path('services/', EditingServiceListView.as_view(), name='editservice_list'),
    path('services/create/', EditingServiceCreateView.as_view(), name='editservice_create'),
    path('services/<int:pk>/', EditingServiceDetailView.as_view(), name='editservice_detail'),
    path('services/<int:pk>/update/', EditingServiceUpdateView.as_view(), name='editservice_update'),
    path('projects/', ProjectListView.as_view(), name='project_list'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('projects/create/', ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('editor/<int:pk>/', EditorProfileDetailView.as_view(), name='editorprofile_detail'),
    path('editor/<int:pk>/update/', EditorProfileUpdateView.as_view(), name='editorprofile_update'),
    path('services/<int:pk>/revision/', RevisionCreateView.as_view(), name='revision_create'),
    path('services/<int:pk>/comment/', CommentCreateView.as_view(), name='comment_create'),
]

shop/urls.py
from django.urls import path
from .views import CategoryCreateView, ShopHubView, CategoryListView, CategoryDetailView, CategoryDeleteView, CategoryUpdateView, ProductListView, ProductCreateView, ProductUpdateView, ProductDetailView, ProductDeleteView, OrderListView, OrderDetailView, AddressOrderListView, AddressDetailView, WishListView, WishDetailView, CouponCreateView, CouponListView, CouponUpdateView, CouponDetailView, CouponDeleteView, CartListView

app_name = 'shop'
urlpatterns = [
    path('shop0-hub/', ShopHubView.as_view(), name='shop-hub'),
    path('category/', CategoryCreateView.as_view(), name='category-create' ),
    path('category/update/<slug:slug>/', CategoryUpdateView.as_view(), name='category-update'),
    path('category/list/', CategoryListView.as_view(), name='category-list'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category-detail'),
    path('delete/category/<slug:slug>/', CategoryDeleteView.as_view(), name='category-delete'),


#product
    path('product/', ProductListView.as_view(), name='prod-list'),
    path('create/product/', ProductCreateView.as_view(), name='prod-create'),
    path('update/product/<slug:slug>/', ProductUpdateView.as_view(), name='prod-update'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='prod-det'),
    path('delete/product/<slug:slug>/', ProductDeleteView.as_view(), name='prod-delete'),

#order
    path('order/', OrderListView.as_view(), name='order-List'),
    path('order/detail/<slug:slug>/', OrderDetailView.as_view(), name='order-detail'),

#   Address
    path('address/order/', AddressOrderListView.as_view(), name='order-address'),
    path('address/detail/<slug:slug>', AddressDetailView.as_view(), name='address-detail'),


#WishList
    path('wishlist/', WishListView.as_view(), name='wish-list'),
    path('wishlist/detail/', WishDetailView.as_view(), name='wish-detail'),


#Coupon
    path('coupon/create/', CouponCreateView.as_view(), name='coupon-create'),
    path('coupon/list/', CouponListView.as_view(), name='coupon-list'),
    path('coupon/update/', CouponUpdateView.as_view(), name='coupon-update'),
    path('coupon/detail/<slug:slug>/', CouponDetailView.as_view(), name='coupon-detail'),
    path('coupon/delete/<slug:slug>/', CouponDeleteView.as_view(), name='coupon-delete'),

#cart
    path('cart/list/', CartListView.as_view(), name='cart-list'),





]

tech/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('custom/', include('custom.urls')),
    path('bms/', include('bms.urls')),
    path('api/bms/', include('bms.api_urls')),
    path('portfolio/', include('portfolio.urls')),
    path('api/portfolio/', include('portfolio.api_urls')),
    path('skillsync/', include('skillsync.urls')),
    path('api/skillsync/', include('skillsync.api_urls')),
    path('editing/', include('editing.urls')),
    path('api/editing/', include('editing.api_urls')),
    path('shop/', include('shop.urls')),
    path('api/shop/', include('shop.api_urls')),
    path('todo/', include('todo.urls')),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path

from . views import *

app_name = 'todo'
urlpatterns = [
    path('todo/', ToDoHubView.as_view(), name='todo-hub'),
    # TaskList URLs
    path('tasklists/', TaskListListView.as_view(), name='tasklist-list'),
    path('tasklists/create/', TaskListCreateView.as_view(), name='tasklist-create'),
    path('tasklists/<int:pk>/', TaskListDetailView.as_view(), name='tasklist-detail'),
    path('tasklists/<int:pk>/update/', TaskListUpdateView.as_view(), name='tasklist-update'),
    path('tasklists/<int:pk>/delete/', TaskListDeleteView.as_view(), name='tasklist-delete'),

    # Task URLs
    path('tasks/', TaskListView.as_view(), name='task-list'),
    path('tasks/create/', TaskCreateView.as_view(), name='task-create'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('tasks/<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),

    # Comment URLs
    path('tasks/<int:task_id>/comments/create/', CommentCreateView.as_view(), name='comment-create'),
    path('comments/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),

    # Reminder URLs
    path('tasks/<int:task_id>/reminders/create/', ReminderCreateView.as_view(), name='reminder-create'),
    path('reminders/<int:pk>/delete/', ReminderDeleteView.as_view(), name='reminder-delete'),

    # Tag URLs
    path('tags/', TagListView.as_view(), name='tag-list'),
    path('tags/create/', TagCreateView.as_view(), name='tag-create'),
    path('tags/<int:pk>/update/', TagUpdateView.as_view(), name='tag-update'),
    path('tags/<int:pk>/delete/', TagDeleteView.as_view(), name='tag-delete'),

]

base/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class IndexView(TemplateView):
    template_name = 'base/index.html'


class CommunityView(TemplateView):
    template_name = 'base/community.html'


class InforView(TemplateView):
    template_name = 'base/infor.html'



class ErrorView(TemplateView):
    template_name = 'base/error.html'

class HelpCenterView(TemplateView):
    template_name = 'base/help-center.html'

dashboard/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

User = get_user_model()


class BaseDashboardView(LoginRequiredMixin, TemplateView):
    group_name = None

    def dispatch(self, request, *args, **kwargs):
        if not request.user.groups.filter(name=self.group_name).exists():
            messages.error(request, "You are not authorized to access this page.")
            return redirect('base:index')
        return super().dispatch(request, *args, **kwargs)



class UserDashboardView(BaseDashboardView):
    template_name = 'dashboard/user_dashboard.html'
    group_name = 'default'




class SuperDashboard(BaseDashboardView):
    template_name = 'dashboard/super_dash.html'
    group_name = None
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return super(BaseDashboardView, self).dispatch(request, *args, **kwargs)

        return super().dispatch(request, *args, **kwargs)




class AgentDashboardView(BaseDashboardView):
    template_name = 'dashboard/agent_dash.html'
    group_name = 'agent'



class ManagerDashboard(BaseDashboardView):
    template_name = 'dashboard/manger_dash.html'
    group_name = 'manager'

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en" class="h-full">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Sites Dashboard</title>
    <script src="//unpkg.com/alpinejs" defer></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <style>
        [x-cloak] { display: none !important; }
        .gradient-border {
            background: linear-gradient(white, white) padding-box,
                        linear-gradient(145deg, #6D28D9, #3B82F6) border-box;
            border: 2px solid transparent;
        }
    </style>
</head>
<body class="bg-gray-50 h-full" x-data="{
    sidebarOpen: window.innerWidth >= 768,
    profileOpen: false,
    sites: [
        { id: 1, name: 'Fashion Store', type: 'ecom', status: 'active',
          visitors: '2.4k', sales: '$12.4k', url: 'store.example.com' },
        { id: 2, name: 'Design Portfolio', type: 'portfolio', status: 'draft',
          visitors: '0', projects: 15, url: 'portfolio.example.com' }
    ],
    currentView: 'all',
    showCreateModal: false,
    isMobile: window.innerWidth < 768,
}">
<div class="min-h-full flex flex-col md:flex-row">
    <!-- Desktop Sidebar -->
    <aside class="bg-white w-64 shadow-lg transition-all duration-300 z-30 hidden md:block"
           :class="sidebarOpen ? 'translate-x-0' : '-translate-x-full'">
        <div class="p-6 border-b border-gray-200">
            <h2 class="text-xl font-bold text-gray-800">My Workspace</h2>
            <p class="text-sm text-gray-500">@{{ user.email }}</p>
        </div>

        <nav class="p-4 space-y-2">
    <a href="{% url 'bms:bms-hub' %}"
       class="w-full text-left p-3 rounded-lg hover:bg-gray-100 flex items-center"
       :class="currentView === 'all' && 'bg-purple-50'">
        <i class='bx bx-grid-alt mr-3 text-purple-600'></i>
        <span class="text-gray-700">Bms</span>
    </a>

    <div class="pl-4">
        <h3 class="text-sm text-gray-500 mb-2">Site Types</h3>
        <a href="{% url 'shop:shop-hub' %}"
           class="w-full text-left p-2 rounded-lg hover:bg-gray-100 flex items-center"
           :class="currentView === 'ecom' && 'bg-purple-50'">
            <i class='bx bx-store mr-3 text-blue-600'></i>
            <span class="text-gray-700">E-commerce</span>
        </a>
        <a href="{% url 'portfolio:portfolio-hub' %}"
           class="w-full text-left p-2 rounded-lg hover:bg-gray-100 flex items-center"
           :class="currentView === 'portfolio' && 'bg-purple-50'">
            <i class='bx bx-palette mr-3 text-green-600'></i>
            <span class="text-gray-700">Portfolios</span>
        </a>
         <a href="{% url 'skillsync:skill-hub' %}"
           class="w-full text-left p-2 rounded-lg hover:bg-gray-100 flex items-center"
           :class="currentView === 'portfolio' && 'bg-purple-50'">
            <i class='bx bx-book mr-3 text-green-600'></i>
            <span class="text-gray-700">SkillSync</span>
        </a>
        <a href="{% url 'editing:editing-hub' %}"
           class="w-full text-left p-2 rounded-lg hover:bg-gray-100 flex items-center"
           :class="currentView === 'portfolio' && 'bg-purple-50'">
            <i class='bx bx-movie-play mr-3 text-blue-600'></i>
            <span class="text-gray-700">VideoEditing</span>
        </a>
         <a href="{% url 'todo:todo-hub' %}"
           class="w-full text-left p-2 rounded-lg hover:bg-gray-100 flex items-center"
           :class="currentView === 'portfolio' && 'bg-purple-50'">
            <i class='bx bx-task text-blue-600'></i>
            <span class="text-gray-700">Todo-hub</span>
        </a>
    </div>
</nav>
    </aside>

    <!-- Main Content -->
    <main class="flex-1 transition-all duration-300 pb-20 md:pb-0"
          :class="sidebarOpen && !isMobile ? 'md:ml-64' : ''">
        <!-- Header -->
        <header class="bg-white shadow-sm p-4 flex justify-between items-center">
            <button @click="sidebarOpen = !sidebarOpen" class="md:hidden">
                <i class='bx bx-menu text-2xl text-gray-700'></i>
            </button>

            <div class="flex items-center space-x-4">
                <div class="relative">
                    {% if user.profile.image %}
                    <img src="{{ user.profile.image.url }}" class="w-8 h-8 rounded-full cursor-pointer"
                          alt="Profile photo

                         @click="profileOpen = !profileOpen">
                      {% else %}
                    <div class="h-8 w-8 rounded-full border-2 border-indigo-300 group-hover:border-indigo-100 transition-colors bg-indigo-100 flex items-center justify-center text-sm font-medium text-indigo-800 cursor-pointer"
                 @click="profileOpen = !profileOpen">
                {{ user.username|first|upper }}
            </div>
        {% endif %}
                    <div x-show="profileOpen"
                         @click.away="profileOpen = false"
                         x-transition:enter="transition ease-out duration-100"
                         x-transition:enter-start="opacity-0 scale-95"
                         x-transition:enter-end="opacity-100 scale-100"
                         x-transition:leave="transition ease-in duration-75"
                         x-transition:leave-start="opacity-100 scale-100"
                         x-transition:leave-end="opacity-0 scale-95"
                         class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 ring-1 ring-black ring-opacity-5 z-50"
                         x-cloak>
                        <div class="px-4 py-2 border-b border-gray-200">
                            <p class="text-sm text-gray-500">Logged in as</p>
                            <p class="text-sm font-medium text-gray-800 truncate">{{ user.email }}</p>
                        </div>

                        <a href="#" class="flex items-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                            <i class='bx bx-user mr-3'></i>
                            Profile
                        </a>

                        <a href="#" class="flex items-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                            <i class='bx bx-envelope mr-3'></i>
                            Email Settings
                        </a>

                        <a href="{% url 'custom:settings-menu' %}" class="flex items-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                            <i class='bx bx-cog mr-3'></i>
                            Settings
                        </a>

                        <div class="border-t border-gray-200">
                            <form method="post" action="{% url 'logout' %}" class="py-1">
                                {% csrf_token %}
                                <button type="submit" class="w-full text-left flex items-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                                    <i class='bx bx-log-out mr-3'></i>
                                    Logout
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        {% block content %}{% endblock %}
    </main>

    <!-- Mobile Navigation Footer -->
    <footer class="fixed bottom-0 left-0 right-0 bg-white shadow-lg md:hidden z-40 border-t border-gray-200">
        <nav class="flex justify-around items-center p-2">
            <button @click="currentView = 'all'"
                    class="flex flex-col items-center p-2 text-sm w-full"
                    :class="currentView === 'all' ? 'text-purple-600' : 'text-gray-500'">
                <i class='bx bx-grid-alt text-xl'></i>
                <span class="text-xs mt-1">All</span>
            </button>

            <button @click="currentView = 'ecom'"
                    class="flex flex-col items-center p-2 text-sm w-full"
                    :class="currentView === 'ecom' ? 'text-blue-600' : 'text-gray-500'">
                <i class='bx bx-store text-xl'></i>
                <span class="text-xs mt-1">E-com</span>
            </button>

            <button @click="currentView = 'portfolio'"
                    class="flex flex-col items-center p-2 text-sm w-full"
                    :class="currentView === 'portfolio' ? 'text-green-600' : 'text-gray-500'">
                <i class='bx bx-palette text-xl'></i>
                <span class="text-xs mt-1">Portfolio</span>
            </button>

            <button @click="profileOpen = !profileOpen"
                    class="flex flex-col items-center p-2 text-sm w-full text-gray-500">
                <i class='bx bx-user text-xl'></i>
                <span class="text-xs mt-1">Profile</span>
            </button>
        </nav>
    </footer>
</div>
</body>
</html>